"""
Blueprint JSON → LemmaTask conversion layer.

This module is completely independent of LangGraph. It is responsible only for
transforming the blueprint schema (generated by `lake build :blueprintJson`) into
the internal runtime schema used by the LangGraph workflow.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TypedDict


# ── Runtime types ─────────────────────────────────────────────────────────────

class LemmaTask(TypedDict):
    """A single lemma/theorem/definition extracted from the blueprint JSON.

    This is the primary unit of work passed into LangGraph nodes.
    """
    name: str                          # e.g. "monotone_tendsto_ge"
    kind: str                          # "definition" | "theorem" | "lemma"
    statement: str                     # LaTeX statement text
    proof_sketch: str | None           # natural-language proof sketch (if any)
    file: str                          # source .lean file path
    start_line: int                    # line range start (1-indexed)
    end_line: int                      # line range end (1-indexed)
    dependencies: list[str]            # LaTeX labels this node depends on


class ProofResult(TypedDict):
    """Result of proving a single lemma."""
    name: str                          # lemma name
    success: bool                      # whether the proof was completed
    error: str | None                  # error message if failed


# ── Blueprint converter ───────────────────────────────────────────────────────

def blueprint_to_tasks(blueprint: list[dict]) -> list[LemmaTask]:
    """Convert a blueprint JSON document into a list of LemmaTask objects.

    The blueprint JSON is the array-of-nodes format generated by
    ``lake build :blueprintJson`` and found at
    ``.lake/build/blueprint/module/<ModuleName>.json``.

    Only entries with ``type == "node"`` are converted; other entries
    (e.g. metadata) are silently skipped.
    """
    tasks: list[LemmaTask] = []

    for node in blueprint:
        if node.get("type") != "node":
            continue

        data = node["data"]

        # Dependencies come from proof usesLabels (LaTeX labels) and uses (Lean names).
        # usesLabels are the canonical dependency edges for the dependency graph.
        proof_data = data.get("proof")
        proof_sketch: str | None = proof_data["text"] if proof_data else None

        # Collect both Lean constant deps and LaTeX label deps
        proof_uses_labels: list[str] = (
            list(proof_data.get("usesLabels", []))
            if proof_data
            else []
        )
        proof_uses: list[str] = (
            list(proof_data.get("uses", []))
            if proof_data
            else []
        )
        # Prefer labels (they're the resolved graph edges); fall back to Lean names
        deps = proof_uses_labels if proof_uses_labels else proof_uses

        loc = data["location"]["range"]
        tasks.append(LemmaTask(
            name=data["name"],
            kind=data["statement"]["latexEnv"],
            statement=data["statement"]["text"],
            proof_sketch=proof_sketch,
            file=data["file"],
            start_line=loc["pos"]["line"],
            end_line=loc["endPos"]["line"],
            dependencies=deps,
        ))

    return tasks


def load_blueprint_json(project_root: str | Path, module_name: str = "LeanWorkspace") -> list[dict]:
    """Load the blueprint JSON file for a given module.

    Args:
        project_root: Path to the Lean project root.
        module_name: Name of the Lean module (default: "LeanWorkspace").

    Returns:
        The parsed blueprint JSON (list of node dicts).
    """
    json_path = (
        Path(project_root)
        / ".lake/build/blueprint/module"
        / f"{module_name}.json"
    )
    with open(json_path, encoding="utf-8") as f:
        return json.load(f)
